/**
 * Dossier Domain Schema
 *
 * Tables for bidirectional focus sync between Fast Agent Panel and Dossier views.
 * Enables agent-orchestrated state management for:
 * - Focus state (text↔chart highlighting)
 * - Annotations (agent-generated chart labels)
 * - Enrichment (cached context for data points)
 */
export declare const dossierFocusState: import("convex/server").TableDefinition<import("convex/values").VObject<{
    currentAct?: "actI" | "actII" | "actIII";
    focusedDataIndex?: number;
    hoveredSpanId?: string;
    activeSectionId?: string;
    focusedSeriesId?: string;
    focusSource?: "chart_hover" | "text_hover" | "agent_tool" | "panel_action";
    userId: import("convex/values").GenericId<"users">;
    briefId: string;
    updatedAt: number;
}, {
    /** User ID for multi-user isolation */
    userId: import("convex/values").VId<import("convex/values").GenericId<"users">, "required">;
    /** Brief/memory ID being viewed */
    briefId: import("convex/values").VString<string, "required">;
    /** Current act (scrolly section) */
    currentAct: import("convex/values").VUnion<"actI" | "actII" | "actIII", [import("convex/values").VLiteral<"actI", "required">, import("convex/values").VLiteral<"actII", "required">, import("convex/values").VLiteral<"actIII", "required">], "optional", never>;
    /** Focused data point index on chart */
    focusedDataIndex: import("convex/values").VFloat64<number, "optional">;
    /** Hovered interactive span ID in text */
    hoveredSpanId: import("convex/values").VString<string, "optional">;
    /** Active section ID in scrolly layout */
    activeSectionId: import("convex/values").VString<string, "optional">;
    /** Chart series currently focused */
    focusedSeriesId: import("convex/values").VString<string, "optional">;
    /** Source of last focus change */
    focusSource: import("convex/values").VUnion<"chart_hover" | "text_hover" | "agent_tool" | "panel_action", [import("convex/values").VLiteral<"chart_hover", "required">, import("convex/values").VLiteral<"text_hover", "required">, import("convex/values").VLiteral<"agent_tool", "required">, import("convex/values").VLiteral<"panel_action", "required">], "optional", never>;
    /** Timestamp of last update */
    updatedAt: import("convex/values").VFloat64<number, "required">;
}, "required", "userId" | "briefId" | "currentAct" | "focusedDataIndex" | "hoveredSpanId" | "activeSectionId" | "focusedSeriesId" | "focusSource" | "updatedAt">, {
    by_user_brief: ["userId", "briefId", "_creationTime"];
    by_user: ["userId", "_creationTime"];
}, {}, {}>;
export declare const dossierAnnotations: import("convex/server").TableDefinition<import("convex/values").VObject<{
    seriesId?: string;
    icon?: string;
    agentThreadId?: string;
    userId: import("convex/values").GenericId<"users">;
    briefId: string;
    dataIndex: number;
    text: string;
    position: "above" | "below" | "left" | "right";
    visibleInActs: ("actI" | "actII" | "actIII")[];
    source: "agent" | "user" | "system";
    createdAt: number;
}, {
    /** User ID for multi-user isolation */
    userId: import("convex/values").VId<import("convex/values").GenericId<"users">, "required">;
    /** Brief/memory ID */
    briefId: import("convex/values").VString<string, "required">;
    /** Chart series this annotation belongs to */
    seriesId: import("convex/values").VString<string, "optional">;
    /** Data point index this annotates */
    dataIndex: import("convex/values").VFloat64<number, "required">;
    /** Annotation text */
    text: import("convex/values").VString<string, "required">;
    /** Position relative to data point */
    position: import("convex/values").VUnion<"above" | "below" | "left" | "right", [import("convex/values").VLiteral<"above", "required">, import("convex/values").VLiteral<"below", "required">, import("convex/values").VLiteral<"left", "required">, import("convex/values").VLiteral<"right", "required">], "required", never>;
    /** Optional icon */
    icon: import("convex/values").VString<string, "optional">;
    /** Which acts this annotation is visible in */
    visibleInActs: import("convex/values").VArray<("actI" | "actII" | "actIII")[], import("convex/values").VUnion<"actI" | "actII" | "actIII", [import("convex/values").VLiteral<"actI", "required">, import("convex/values").VLiteral<"actII", "required">, import("convex/values").VLiteral<"actIII", "required">], "required", never>, "required">;
    /** Was this generated by agent or user? */
    source: import("convex/values").VUnion<"agent" | "user" | "system", [import("convex/values").VLiteral<"agent", "required">, import("convex/values").VLiteral<"user", "required">, import("convex/values").VLiteral<"system", "required">], "required", never>;
    /** Agent thread that created this (if agent source) */
    agentThreadId: import("convex/values").VString<string, "optional">;
    /** Creation timestamp */
    createdAt: import("convex/values").VFloat64<number, "required">;
}, "required", "userId" | "briefId" | "seriesId" | "dataIndex" | "text" | "position" | "icon" | "visibleInActs" | "source" | "agentThreadId" | "createdAt">, {
    by_user_brief: ["userId", "briefId", "_creationTime"];
    by_brief_series: ["briefId", "seriesId", "_creationTime"];
    by_brief_dataIndex: ["briefId", "dataIndex", "_creationTime"];
}, {}, {}>;
export declare const dossierEnrichment: import("convex/server").TableDefinition<import("convex/values").VObject<{
    seriesId?: string;
    agentThreadId?: string;
    entities?: {
        url?: string;
        type: string;
        name: string;
    }[];
    sources?: {
        title?: string;
        url: string;
        retrievedAt: number;
    }[];
    expiresAt?: number;
    userId: import("convex/values").GenericId<"users">;
    briefId: string;
    dataIndex: number;
    createdAt: number;
    title: string;
    context: string;
    lastAccessedAt: number;
}, {
    /** User ID for multi-user isolation */
    userId: import("convex/values").VId<import("convex/values").GenericId<"users">, "required">;
    /** Brief/memory ID */
    briefId: import("convex/values").VString<string, "required">;
    /** Chart series */
    seriesId: import("convex/values").VString<string, "optional">;
    /** Data point index */
    dataIndex: import("convex/values").VFloat64<number, "required">;
    /** Enrichment title */
    title: import("convex/values").VString<string, "required">;
    /** Detailed context from agent */
    context: import("convex/values").VString<string, "required">;
    /** Related entities (companies, people, events) */
    entities: import("convex/values").VArray<{
        url?: string;
        type: string;
        name: string;
    }[], import("convex/values").VObject<{
        url?: string;
        type: string;
        name: string;
    }, {
        name: import("convex/values").VString<string, "required">;
        type: import("convex/values").VString<string, "required">;
        url: import("convex/values").VString<string, "optional">;
    }, "required", "type" | "name" | "url">, "optional">;
    /** Source URLs for citations */
    sources: import("convex/values").VArray<{
        title?: string;
        url: string;
        retrievedAt: number;
    }[], import("convex/values").VObject<{
        title?: string;
        url: string;
        retrievedAt: number;
    }, {
        url: import("convex/values").VString<string, "required">;
        title: import("convex/values").VString<string, "optional">;
        retrievedAt: import("convex/values").VFloat64<number, "required">;
    }, "required", "title" | "url" | "retrievedAt">, "optional">;
    /** Agent thread that created this */
    agentThreadId: import("convex/values").VString<string, "optional">;
    /** Cache expiry (ms since epoch) */
    expiresAt: import("convex/values").VFloat64<number, "optional">;
    /** Creation timestamp */
    createdAt: import("convex/values").VFloat64<number, "required">;
    /** Last access timestamp (for LRU eviction) */
    lastAccessedAt: import("convex/values").VFloat64<number, "required">;
}, "required", "userId" | "briefId" | "seriesId" | "dataIndex" | "agentThreadId" | "createdAt" | "title" | "context" | "entities" | "sources" | "expiresAt" | "lastAccessedAt">, {
    by_user_brief: ["userId", "briefId", "_creationTime"];
    by_brief_dataIndex: ["briefId", "dataIndex", "_creationTime"];
    by_expires: ["expiresAt", "_creationTime"];
}, {}, {}>;
