/**
 * toolCatalog.ts — Static summary of MCP tool metadata for the frontend API docs page.
 *
 * Source of truth lives in packages/mcp-local/src/tools/toolRegistry.ts (338 tools).
 * This file contains a curated subset of ~55 representative tools for the browseable catalog.
 * The full catalog is accessible at /developers.
 */

export interface ToolCatalogEntry {
  name: string;
  category: string;
  description: string;
  complexity: "low" | "medium" | "high";
  phase: "research" | "implement" | "test" | "verify" | "ship" | "meta" | "utility";
  inputFields?: string[];
}

export const TOOL_CATALOG: ToolCatalogEntry[] = [
  // ═══ DEEP SIM (7) ═══
  {
    name: "build_claim_graph",
    category: "deep_sim",
    description: "Construct a causal claim graph from research signals, linking evidence nodes to hypothesis edges with confidence scores.",
    complexity: "high",
    phase: "research",
    inputFields: ["claims", "evidenceNodes", "hypothesisId"],
  },
  {
    name: "run_counterfactual",
    category: "deep_sim",
    description: "Execute a counterfactual simulation: given a causal graph, remove or alter one node and propagate effects.",
    complexity: "high",
    phase: "research",
    inputFields: ["graphId", "removedNodeId", "propagationDepth"],
  },
  {
    name: "score_explanation",
    category: "deep_sim",
    description: "Score a competing explanation against a 6-point boolean evidence checklist (gov source, corroborated, hard numbers, etc.).",
    complexity: "medium",
    phase: "research",
    inputFields: ["explanationText", "evidenceChecklist"],
  },
  {
    name: "merge_claim_graphs",
    category: "deep_sim",
    description: "Merge two or more claim graphs, resolving conflicting edges and deduplicating evidence nodes.",
    complexity: "high",
    phase: "research",
    inputFields: ["graphIds"],
  },
  {
    name: "extract_falsifiable_claims",
    category: "deep_sim",
    description: "Extract falsifiable claims from a text corpus, tagging each with testability score and suggested verification method.",
    complexity: "medium",
    phase: "research",
    inputFields: ["text", "minTestabilityScore"],
  },
  {
    name: "simulate_scenario",
    category: "deep_sim",
    description: "Run a forward simulation from current state using Monte Carlo branching over key uncertainty variables.",
    complexity: "high",
    phase: "research",
    inputFields: ["scenarioConfig", "iterations", "timeHorizon"],
  },
  {
    name: "compare_explanations",
    category: "deep_sim",
    description: "Side-by-side comparison of competing explanations with evidence overlap analysis and Bayesian scoring.",
    complexity: "high",
    phase: "research",
    inputFields: ["explanationIds", "evidencePool"],
  },

  // ═══ RESEARCH (8) ═══
  {
    name: "web_search",
    category: "research_writing",
    description: "Search the web for current information on a topic, returning ranked results with snippets and source URLs.",
    complexity: "low",
    phase: "research",
    inputFields: ["query", "maxResults"],
  },
  {
    name: "polish_academic_text",
    category: "research_writing",
    description: "Improve academic writing: fix grammar, strengthen argumentation, add hedging language, and format citations.",
    complexity: "low",
    phase: "verify",
    inputFields: ["text", "style", "targetAudience"],
  },
  {
    name: "translate_academic",
    category: "research_writing",
    description: "Translate academic text between languages while preserving technical terminology and citation format.",
    complexity: "medium",
    phase: "implement",
    inputFields: ["text", "sourceLang", "targetLang"],
  },
  {
    name: "compress_or_expand_text",
    category: "research_writing",
    description: "Compress text to a target word count or expand with additional detail, preserving key arguments.",
    complexity: "low",
    phase: "implement",
    inputFields: ["text", "targetWords", "mode"],
  },
  {
    name: "query_daily_brief",
    category: "platform",
    description: "Retrieve the latest daily intelligence brief with signal summaries, priority alerts, and recommended actions.",
    complexity: "low",
    phase: "verify",
    inputFields: ["date", "sections"],
  },
  {
    name: "query_funding_entities",
    category: "platform",
    description: "Query funding rounds, investors, and deal flow data for tracked companies and sectors.",
    complexity: "low",
    phase: "research",
    inputFields: ["query", "sector", "stage"],
  },
  {
    name: "query_research_queue",
    category: "platform",
    description: "List pending research tasks with priority scores, deadlines, and assigned agent status.",
    complexity: "low",
    phase: "research",
    inputFields: ["status", "limit"],
  },
  {
    name: "fetch_url",
    category: "web_scraping",
    description: "Fetch and parse a URL, extracting clean text content with metadata (title, author, date, reading time).",
    complexity: "low",
    phase: "research",
    inputFields: ["url", "extractMode"],
  },

  // ═══ VERIFICATION (5) ═══
  {
    name: "start_verification_cycle",
    category: "verification",
    description: "Begin a 6-phase verification cycle: context gathering, implementation review, test coverage, gap analysis, resolution, sign-off.",
    complexity: "medium",
    phase: "verify",
    inputFields: ["title", "scope"],
  },
  {
    name: "log_phase_findings",
    category: "verification",
    description: "Record findings for a verification phase. Marks phase as passed or failed with evidence.",
    complexity: "low",
    phase: "verify",
    inputFields: ["cycleId", "phase", "status", "findings"],
  },
  {
    name: "log_gap",
    category: "verification",
    description: "Log a gap (bug, missing feature, or quality issue) with severity, root cause, and fix strategy.",
    complexity: "low",
    phase: "verify",
    inputFields: ["cycleId", "severity", "description", "rootCause"],
  },
  {
    name: "resolve_gap",
    category: "verification",
    description: "Mark a gap as resolved with resolution summary and verification evidence.",
    complexity: "low",
    phase: "verify",
    inputFields: ["gapId", "resolution", "evidence"],
  },
  {
    name: "get_verification_status",
    category: "verification",
    description: "Get current verification cycle status: phase progress, open gaps by severity, and next recommended action.",
    complexity: "low",
    phase: "verify",
    inputFields: ["cycleId"],
  },

  // ═══ AGENTS (5) ═══
  {
    name: "claim_agent_task",
    category: "parallel_agents",
    description: "Claim a task from the shared task pool for parallel agent execution. Prevents double-assignment.",
    complexity: "low",
    phase: "verify",
    inputFields: ["taskId", "agentId"],
  },
  {
    name: "release_agent_task",
    category: "parallel_agents",
    description: "Release a claimed task back to the pool (on failure or reassignment).",
    complexity: "low",
    phase: "implement",
    inputFields: ["taskId", "reason"],
  },
  {
    name: "list_agent_tasks",
    category: "parallel_agents",
    description: "List all tasks in the pool with status, owner, and priority. Supports filtering by status.",
    complexity: "low",
    phase: "ship",
    inputFields: ["status", "limit"],
  },
  {
    name: "broadcast_agent_message",
    category: "parallel_agents",
    description: "Send a message to all agents in a swarm. Used for coordination signals and shared context updates.",
    complexity: "low",
    phase: "implement",
    inputFields: ["message", "swarmId"],
  },
  {
    name: "get_agent_mailbox",
    category: "parallel_agents",
    description: "Read messages from an agent's inbox. Returns unread messages sorted by priority.",
    complexity: "low",
    phase: "implement",
    inputFields: ["agentId", "unreadOnly"],
  },

  // ═══ MISSIONS (5) ═══
  {
    name: "plan_decompose_mission",
    category: "mission_harness",
    description: "Decompose a high-level mission into subtasks with dependency graph, budget allocation, and success criteria.",
    complexity: "high",
    phase: "research",
    inputFields: ["missionDescription", "constraints", "budget"],
  },
  {
    name: "judge_verify_subtask",
    category: "mission_harness",
    description: "Judge whether a subtask output meets its acceptance criteria. Returns pass/fail with detailed rationale.",
    complexity: "high",
    phase: "verify",
    inputFields: ["subtaskId", "output", "criteria"],
  },
  {
    name: "judge_request_retry",
    category: "mission_harness",
    description: "Request a retry for a failed subtask with modified approach, budget reallocation, or scope adjustment.",
    complexity: "high",
    phase: "verify",
    inputFields: ["subtaskId", "retryStrategy"],
  },
  {
    name: "get_mission_status",
    category: "mission_harness",
    description: "Get full mission status: subtask progress, budget burn, blockers, and estimated completion.",
    complexity: "medium",
    phase: "verify",
    inputFields: ["missionId"],
  },
  {
    name: "abort_mission",
    category: "mission_harness",
    description: "Abort a running mission, cleaning up in-flight subtasks and logging abort reason for postmortem.",
    complexity: "medium",
    phase: "ship",
    inputFields: ["missionId", "reason"],
  },

  // ═══ TRAJECTORY (5) ═══
  {
    name: "ingest_temporal_observation",
    category: "temporal_intelligence",
    description: "Ingest a timestamped observation into the temporal intelligence graph for trend detection.",
    complexity: "low",
    phase: "utility",
    inputFields: ["observation", "timestamp", "source"],
  },
  {
    name: "detect_temporal_signal",
    category: "temporal_intelligence",
    description: "Detect emerging signals from temporal observation clusters. Returns signal strength and confidence.",
    complexity: "medium",
    phase: "research",
    inputFields: ["timeWindow", "minStrength"],
  },
  {
    name: "build_causal_chain",
    category: "temporal_intelligence",
    description: "Build a causal chain linking temporal signals to outcomes with confidence intervals.",
    complexity: "high",
    phase: "research",
    inputFields: ["signalIds", "outcomeId"],
  },
  {
    name: "get_trajectory_analysis",
    category: "self_eval",
    description: "Analyze the trajectory of a tool-use session: efficiency score, dead ends, and optimization suggestions.",
    complexity: "medium",
    phase: "utility",
    inputFields: ["sessionId"],
  },
  {
    name: "log_tool_call",
    category: "self_eval",
    description: "Log a tool call for trajectory analysis. Captures timing, input size, output quality, and error status.",
    complexity: "low",
    phase: "test",
    inputFields: ["toolName", "duration", "success"],
  },

  // ═══ SECURITY (5) ═══
  {
    name: "validate_url",
    category: "security",
    description: "Validate a URL against SSRF rules, blocklists, and protocol restrictions before fetching.",
    complexity: "low",
    phase: "verify",
    inputFields: ["url"],
  },
  {
    name: "redact_credentials",
    category: "security",
    description: "Scan text for credentials (API keys, tokens, passwords) and redact them with placeholder markers.",
    complexity: "low",
    phase: "verify",
    inputFields: ["text"],
  },
  {
    name: "audit_tool_access",
    category: "security",
    description: "Audit which tools an agent accessed, when, and with what parameters. Returns compliance report.",
    complexity: "medium",
    phase: "verify",
    inputFields: ["agentId", "timeWindow"],
  },
  {
    name: "run_recon",
    category: "reconnaissance",
    description: "Run automated reconnaissance on a codebase or system: file tree, dependency graph, entry points, and risk areas.",
    complexity: "medium",
    phase: "ship",
    inputFields: ["target", "depth"],
  },
  {
    name: "get_recon_summary",
    category: "reconnaissance",
    description: "Get a summary of reconnaissance findings: architecture overview, hotspots, and recommended next steps.",
    complexity: "low",
    phase: "research",
    inputFields: ["reconId"],
  },

  // ═══ SESSION (3) ═══
  {
    name: "save_session_note",
    category: "session_memory",
    description: "Save a note to persistent session memory. Survives context compaction and session restarts.",
    complexity: "low",
    phase: "utility",
    inputFields: ["content", "tags"],
  },
  {
    name: "load_session_notes",
    category: "session_memory",
    description: "Load session notes from persistent storage. Supports filtering by tag and date range.",
    complexity: "low",
    phase: "utility",
    inputFields: ["tags", "since"],
  },
  {
    name: "refresh_task_context",
    category: "session_memory",
    description: "Refresh working context: active verification cycles, open gaps, recent learnings, and tool call stats.",
    complexity: "low",
    phase: "utility",
    inputFields: [],
  },

  // ═══ PROGRESSIVE DISCOVERY (3) ═══
  {
    name: "discover_tools",
    category: "progressive_discovery",
    description: "Search and discover tools by keyword, category, or semantic similarity. Supports pagination and result expansion.",
    complexity: "low",
    phase: "meta",
    inputFields: ["query", "category", "offset", "limit", "expand"],
  },
  {
    name: "get_tool_quick_ref",
    category: "progressive_discovery",
    description: "Get quick reference for a tool: what it does, what to call next, and multi-hop BFS traversal of related tools.",
    complexity: "low",
    phase: "meta",
    inputFields: ["toolName", "depth"],
  },
  {
    name: "get_workflow_chain",
    category: "progressive_discovery",
    description: "Get a recommended sequence of tool calls for a workflow (e.g., new_feature, fix_bug, security_audit).",
    complexity: "low",
    phase: "meta",
    inputFields: ["workflow"],
  },

  // ═══ META (3) ═══
  {
    name: "findTools",
    category: "meta",
    description: "Front-door tool: find relevant tools for a task description. Returns ranked suggestions with confidence scores.",
    complexity: "low",
    phase: "meta",
    inputFields: ["task"],
  },
  {
    name: "getMethodology",
    category: "meta",
    description: "Get the NodeBench methodology guide: 7-step flywheel, verification phases, and agent contract rules.",
    complexity: "low",
    phase: "meta",
    inputFields: [],
  },
  {
    name: "check_mcp_setup",
    category: "meta",
    description: "Validate MCP server setup: check 11 domains, verify connectivity, and optionally generate setup files.",
    complexity: "low",
    phase: "meta",
    inputFields: ["generate_setup"],
  },

  // ═══ OBSERVABILITY (3) ═══
  {
    name: "get_system_pulse",
    category: "observability",
    description: "Get real-time system health: API latency, error rates, active agents, and resource utilization.",
    complexity: "low",
    phase: "meta",
    inputFields: [],
  },
  {
    name: "get_drift_report",
    category: "observability",
    description: "Detect configuration drift: schema changes, permission changes, and unexpected state mutations.",
    complexity: "low",
    phase: "utility",
    inputFields: ["since"],
  },
  {
    name: "run_self_heal",
    category: "observability",
    description: "Attempt automatic remediation of detected issues: restart stuck agents, clear stale locks, repair indices.",
    complexity: "medium",
    phase: "verify",
    inputFields: ["issueId"],
  },
];

/** All unique categories in the catalog, sorted alphabetically */
export const CATALOG_CATEGORIES = [
  ...new Set(TOOL_CATALOG.map((t) => t.category)),
].sort();

/** Category display names (human-readable) */
export const CATEGORY_LABELS: Record<string, string> = {
  deep_sim: "Deep Simulation",
  research_writing: "Research & Writing",
  platform: "Platform Queries",
  web_scraping: "Web Scraping",
  verification: "Verification",
  parallel_agents: "Parallel Agents",
  mission_harness: "Mission Harness",
  temporal_intelligence: "Temporal Intelligence",
  self_eval: "Self Evaluation",
  security: "Security",
  reconnaissance: "Reconnaissance",
  session_memory: "Session Memory",
  progressive_discovery: "Progressive Discovery",
  meta: "Meta / Setup",
  observability: "Observability",
};

/** Category → count of tools in the full registry (304 total) */
export const FULL_REGISTRY_COUNTS: Record<string, number> = {
  local_file: 19,
  mission_harness: 15,
  ui_ux_dive_v2: 14,
  parallel_agents: 13,
  bootstrap: 11,
  platform: 11,
  ui_ux_dive: 11,
  self_eval: 9,
  verification: 8,
  research_writing: 8,
  agent_traverse: 8,
  observability: 8,
  reconnaissance: 7,
  web_scraping: 7,
  temporal_intelligence: 7,
  deep_sim: 7,
  eval: 6,
  gaia_solvers: 6,
  thompson_protocol: 6,
  flicker_detection: 5,
  seo: 5,
  mcp_bridge: 5,
  local_dashboard: 5,
  design_governance: 5,
  context_sandbox: 5,
  quality_gate: 4,
  learning: 4,
  flywheel: 4,
  vision: 4,
  documentation: 4,
  figma_flow: 4,
  voice_bridge: 4,
  email: 4,
  rss: 4,
  skill_update: 4,
  qa_orchestration: 4,
  visual_qa: 4,
  engine_context: 4,
  research_optimizer: 3,
  github: 3,
  llm: 3,
  security: 3,
  benchmark: 3,
  progressive_discovery: 3,
  meta: 3,
  session_memory: 3,
  git_workflow: 3,
  architect: 3,
  ui_capture: 2,
  web: 2,
  boilerplate: 2,
  toon: 2,
  pattern: 2,
  critter: 1,
};

export const TOTAL_TOOLS = 304;
